### ISSUE TITLE
quality check for transcript

### ISSUE THREAD

**Issue by jcolomb** [open-life-science/ols3-cohort-talks-and-transcripts#3]
I will do the open hardware one, watch for a PR later tonite :)
I will indeed do both
https://github.com/open-life-science/ols3-cohort-talks-and-transcripts/blob/main/en_transcripts/Open-Source-Science-Hardware.srt
and 

https://github.com/open-life-science/ols3-cohort-talks-and-transcripts/blob/main/en_transcripts/Open-Science-Hardware.srt

**Comment by BatoolMM** [comment]
Thank you again @jcolomb for fixing the transcripts. I made further changes to the transcripts and the translation workflow. In case you wanted to submit any translation in the future, we are using Crowdin which seamlessly integrates with GitHub and leverages an existing Translation Memory and Glossary. Also, individuals can submit a translation for individual strings/sentences rather than translating complete transcript and use machines translation (e.g. Google Translate, ...) to help them in the process within Crowdin.

You can explore the workflow through [our page in Crowdin](https://crowdin.com/project/ols3) and [the contribution guidelines](https://github.com/open-life-science/ols3-cohort-talks-and-transcripts/blob/main/CONTRIBUTING%E2%80%8B.md). 

This is not to overwhelm you but just to let you know about the new workflow. Please let me know if you have any questions!

**Comment by jcolomb** [comment]
that looks amazing, will look into this when I get time! Thank you for letting me know. Should we close this issue?

**Comment by BatoolMM** [comment]
Thank you!!
